# Generated by Django 4.2.9 on 2024-01-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_deleted',
        ),
    ]
