# Generated by Django 4.2.9 on 2024-01-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_descriotion_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(default=1, related_name='products', to='store.promotion'),
        ),
    ]
