# Generated by Django 4.2.9 on 2024-01-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('C', 'Canceled'), ('D', 'Deleted')], default='C', max_length=1),
        ),
    ]
